#!/usr/bin/env python3
"""
Generate the data for the galaxy preview harness.

Writes frontend/preview-galaxy-data.js - three candidate galaxies at
weak / agreed / strong clumping on one fixed seed, produced by the REAL
generator so the preview page cannot drift from the game. The page
renders them with the shipped GalaxyMap.renderStar.

Run: uv run python scripts/preview_galaxy.py
"""

import json
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from backend.core.game_objects.star import Star  # noqa: E402
from backend.services import star_field  # noqa: E402
from backend.services.galaxy_generator import (  # noqa: E402
    GalaxyGenerator, STAR_DENSITY, STAR_MARGIN, UNIVERSE_SIZES
)

SEED = 4242
SIZE = "medium"
CANDIDATES = [
    ("weak", 0.20),
    ("agreed", star_field.CLUMPING_STRENGTH),
    ("strong", 0.80),
]

OUT = Path(__file__).resolve().parents[1] / "frontend" / "preview-galaxy-data.js"


def build(clumping):
    """One galaxy's stars: position plus the fields the renderer reads."""
    width, height = UNIVERSE_SIZES[SIZE]
    count = width * height // (STAR_DENSITY * STAR_DENSITY)
    generator = GalaxyGenerator(SEED)
    positions = star_field.generate_positions(
        width, height, count, STAR_MARGIN, SEED, random.Random(SEED),
        clumping=clumping)

    stars = []
    for index, (x, y) in enumerate(positions):
        star = Star()
        star.name = f"S{index}"
        # Same spectral draw the generator uses, so the size mix on the
        # sheet is the size mix in a real game
        generator._assign_spectral_class(star)
        stars.append({
            "name": star.name,
            "position_x": x,
            "position_y": y,
            "spectral_class": star.spectral_class,
            "star_radius": round(star.star_radius, 3),
            "colonists": 0,
            "owner": 0,
        })
    return stars


def main():
    width, height = UNIVERSE_SIZES[SIZE]
    data = {
        "seed": SEED,
        "size": SIZE,
        "width": width,
        "height": height,
        "candidates": [
            {"label": label, "clumping": clumping, "stars": build(clumping)}
            for label, clumping in CANDIDATES
        ],
    }
    OUT.write_text(
        "// Generated by scripts/preview_galaxy.py - do not edit by hand.\n"
        "window.PREVIEW_GALAXY = " + json.dumps(data) + ";\n",
        encoding="utf-8")
    for candidate in data["candidates"]:
        print(f"{candidate['label']:8s} clumping {candidate['clumping']:.2f} "
              f"{len(candidate['stars'])} stars")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
